// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC6StBpP9fARgP5_M4FtGTe9SuHir8UvM',
    appId: '1:417332715258:web:e9170c97519d2a0194f343',
    messagingSenderId: '417332715258',
    projectId: 'flutterfire-ui-codelab-1844c',
    authDomain: 'flutterfire-ui-codelab-1844c.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-1844c.firebasestorage.app',
    measurementId: 'G-FB0ZV0C4DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0eM-ycL42N3FBJd-4HEc971Mix9dfbiQ',
    appId: '1:417332715258:android:8f61395ca2947c4c94f343',
    messagingSenderId: '417332715258',
    projectId: 'flutterfire-ui-codelab-1844c',
    storageBucket: 'flutterfire-ui-codelab-1844c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjuqmtA_3PhLx7-a9wgXach6hFgf1FH0',
    appId: '1:417332715258:ios:fe3944b33b9c2e7694f343',
    messagingSenderId: '417332715258',
    projectId: 'flutterfire-ui-codelab-1844c',
    storageBucket: 'flutterfire-ui-codelab-1844c.firebasestorage.app',
    iosBundleId: 'com.example.ibites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjuqmtA_3PhLx7-a9wgXach6hFgf1FH0',
    appId: '1:417332715258:ios:fe3944b33b9c2e7694f343',
    messagingSenderId: '417332715258',
    projectId: 'flutterfire-ui-codelab-1844c',
    storageBucket: 'flutterfire-ui-codelab-1844c.firebasestorage.app',
    iosBundleId: 'com.example.ibites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC6StBpP9fARgP5_M4FtGTe9SuHir8UvM',
    appId: '1:417332715258:web:ddbda8236b0f2da694f343',
    messagingSenderId: '417332715258',
    projectId: 'flutterfire-ui-codelab-1844c',
    authDomain: 'flutterfire-ui-codelab-1844c.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-1844c.firebasestorage.app',
    measurementId: 'G-9THQQMR02D',
  );
}
